### ISSUE TITLE
Can't download jar with Maven

### ISSUE THREAD

**Issue by RamiKhawaly** [RootSoft/ONVIF-Java#4]
I'm adding the suggested dependency but when i build the project i get the following error: 
Failed to collect dependencies at be.teletask.onvif:onvif:jar:1.0.0: Failed to read artifact descriptor for be.teletask.onvif:onvif:jar:1.0.0: Could not transfer artifact be.teletask.onvif:onvif:pom:1.0.0 from/to Eclipse repo (https://repo.eclipse.org/content/groups/releases/): Server chose TLSv1, but that protocol version is not enabled or not supported by the client

is there any resolution for such a problem?

**Comment by chengpengvb** [comment]
一台设备都找不到，在多网卡的情况下是不是要设置IP地址

**Comment by jeancc** [comment]
Add the correct repository to the pom:

 <repositories>
    <repository>
      <id>jcenter</id>
      <name>JCenter</name>
      <url>http://jcenter.bintray.com</url>
    </repository>    
  </repositories>

**Comment by jeancc** [comment]
Add the correct repository to the pom.xml

```
 <repositories>
    <repository>
      <id>jcenter</id>
      <name>JCenter</name>
      <url>http://jcenter.bintray.com</url>
    </repository>    
  </repositories>
```
